name: Release workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Build, test, publish to NPM and generate release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure workflow user (to generate release notes)
        run: |
          git config --global user.name "marcelovicentegc"
          git config --global user.email "marcelovicentegc@gmail.com"

      - name: Publish
        run: pnpm lerna publish --yes --force-publish --create-release github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
