name: Release workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - run: echo "Release workflow is a work in progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
